apiVersion: v1
kind: Service
metadata:
  name: hello-world-js-service              # Service Name
spec:
  selector:
    app.kubernetes.io/name: hello-world-js  # App to Match
  ports:
  - name: service-port                      # Port Name
    protocol: TCP
    port: 80                                # Exposed Port
    targetPort: 80                          # Container Port