apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hello-world-js-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: gitUrl
      value: https://github.com/josefinarcasanova/demo-apps
    - name: gitRevision
      value: main
    - name: pathToContext
      value: hello-world-js
    - name: deployment_yaml
      value: hello-world-js/deployment.yaml
    - name: imageUrl
      value: us.icr.io/jrcasan-icr-namespace/hello-world-js-pipeline
    - name: imageTag
      value: latest
    - name: dockerfilePath
      value: hello-world-js/Dockerfile
  serviceAccountName: pipeline-account
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: pvc-source-pipeline