kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world-js
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-world-js
  template:
    metadata:
      labels:
        run: hello-world-js
    spec:
      containers:
        - name: hello-world-js
          image: us.icr.io/jrcasan-icr-namespace/hello-world-js:latest # TODO: take image as parameter
          ports:
            - name: http-server
              containerPort: 8080   # TODO: take port from .env
      imagePullSecrets:
        - name: all-icr-io # TODO: take secret as parameter
      # volumeMounts:
      #   - name: vm-pipeline
      #     mountPath: /mount-path
      # volumes:
      # - name: volume-pipeline
      #   persistentVolumeClaim:
      #     claimName: pvc-pipeline

        