apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: hello-world-js-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: gitUrl
      value: https://github.com/josefinarcasanova/demo-apps
    - name: gitRevision
      value: master
    - name: pathToContext
      value: hello-world-js
    - name: deployment_yaml
      value: hello-world-js/deployment.yaml
    - name: imageUrl
      value: us.icr.io/jrcasan-demo-apps/hello-world-js
    - name: imageTag
      value: latest
  serviceAccountName: pipeline-account
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: pvc-pipeline